# Generated by Django 6.0.5 on 2026-05-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_usermovieaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thriller_clip',
            field=models.FileField(blank=True, help_text='Short 30-second preview clip', null=True, upload_to='thrillers/'),
        ),
    ]
