# Generated by Django 6.0.5 on 2026-05-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_director_movie_rating_movie_release_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.category'),
        ),
    ]
