# Generated by Django 6.0.5 on 2026-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_category_movie_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
